### ISSUE TITLE
请问有演示demo吗

### ISSUE THREAD

**Issue by Yakumo-Yukari** [JabinGP/demo-chatroom#1]

**Comment by JabinGP** [comment]
抱歉，项目前端正在开发中，过几天才能开发完，到时候会完善README.md的

**Comment by Yakumo-Yukari** [comment]
> 抱歉,项目前端正在开发中,过几天才能开发完,到时候会完善README.md的

哦哦  给你推荐个 不错的 聊天室  http://233.nie.im  这个聊天室 你可以参考下  好像还接入了  讯飞还是百度语言 可以语音读出用户发出的消息

**Comment by JabinGP** [comment]
非常感谢
