### ISSUE TITLE
自己发送的消息 为什么不在右侧显示呢

### ISSUE THREAD

**Issue by Yakumo-Yukari** [JabinGP/demo-chatroom#2]
感觉这样显示会更好的区分自己和别人的消息吧

**Comment by JabinGP** [comment]
聊天室是这样的，毕竟不是微信或者qq的群，如果自己发的消息要放右边的话，要设计一个头像，然后把时间隐蔽显示才比较好看一点。


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)
